### PR TITLE
python3 support 

### PR DESCRIPTION
**Pull request by gescheit**
Almost all work made by 2to3. Seems all works as early, except TestOptimizer.test_empty_set. Its failed with: "    def test_empty_set(self):
        "Test removing an empty literal set"
        s = ast.LiteralSet([])
        c, r = optimizer.optimization_pass(s)
>       assert c == 1
E       assert 0 == 1
". Please, check this problem :)

### CODE REVIEW

**Comment by armon** [comment]
I think this breaks python 2 compatibility right? We need to make sure that is also retained.

**Comment by gescheit** [comment]
I fixed compatibility with python 2, but py.test-3 still gives error.

**Comment by gescheit** [comment]
Bump

**Comment by armon** [comment]
Thanks! I'll take a look at the tests

**Comment by armon** [comment]
@gescheit Tests are fixed in master!

**Pull request merged**
